### ISSUE TITLE
Errors on both iOS and macOS

### ISSUE THREAD

**Issue by maxbeech** [xtyxtyx/unix_disk_space#1]
Hi there!

I'm trying to follow your example doc, however after installing, trying to run the first line (`final disks = await diskSpace();`) causes the following error messages:

On iOS:
`[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: ProcessException: Operation not permitted
  Command: df -kPT
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      _run (package:unix_disk_space/src/unix_disk_space.dart:49:32)
#5      UnixDiskSpace.call (package:unix_disk_space/src/unix_disk_space.dart:58:12)`

On macOS:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: -1
#0      List._setIndexed (dart:core-patch/growable_array.dart:262:73)
#1      List.[]= (dart:core-patch/growable_array.dart:258:5)
#2      getColumnBoundaries (package:unix_disk_space/src/unix_disk_space.dart:21:13)
#3      parseOutput.sync_op (package:unix_disk_space/src/unix_disk_space.dart:27:22)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:181:26)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:50:28)
#8      Iterable.toList (dart:core/iterable.dart:366:12)
#9      _run (package:unix_disk_space/src/unix_disk_space.dart:50:37)
`

Any ideas would be hugely appreciated!

_Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (3 months ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0_

Many thanks!

**Comment by xtyxtyx** [comment]
Thanks for interest in this package!

This package acts as a parser of the `df` command and has many limitations.  If you want a more solid way to get disk usage information I recommend using `dart:ffi` to call native functions such as `statvfs`, especially on iOS where executing command isn't possible.

**Comment by maxbeech** [comment]
Awesome thank you!!!
